Provider/src/main/java/dev/openfeature/contrib/providers/ConfidenceFeatureProvider.kt, Provider/src/test/java/dev/openfeature/contrib/providers/ConfidenceFeatureProviderTests.kt
Similarly to how this error is handled in the Swift Provider: https://github.com/spotify/confidence-openfeature-provider-swift/pull/24/files#diff-1bad310998a7169fc07cc21c6d84c6ff339070d2559f7c3406b2dfc9fc76dc08R205-R211
A targeting key error can happen when a custom field in the EvaluationContext is set from the backend to be the targeting key, and the format of such EvaluationContext's field is not among the allowed types for targeting key values (at the moment of writing, a targeting key field must be a String field).
=> Handle Targeting Key error from backend

.github/workflows/ci.yaml
Make sure we run the lighter lint jobs first.
=> ci: update run order of ci

Provider/src/main/java/dev/openfeature/contrib/providers/ConfidenceFeatureProvider.kt, Provider/src/test/java/dev/openfeature/contrib/providers/ConfidenceFeatureProviderTests.kt
* Stale event when the context is changed
* Provider Ready event when the fetch is completed after a context change
* new values are updated in the cache after a successful fetch following a context change.
=> fix: On context change

Provider/src/main/java/com/spotify/confidence/client/ConfidenceRemoteClient.kt
A new field was added to the resolve response. This makes the resolves crash due to the default behaviour of this flag.
=> fix: do not fail network deserialization on unknown fields

.github/workflows/ci.yaml, Provider/src/main/java/com/spotify/confidence/ConfidenceFeatureProvider.kt, Provider/src/main/java/com/spotify/confidence/apply/FlagApplierWithRetries.kt, Provider/src/main/java/com/spotify/confidence/cache/DiskStorage.kt, Provider/src/main/java/com/spotify/confidence/cache/StorageFileCache.kt, Provider/src/test/java/com/spotify/confidence/ConfidenceFeatureProviderTests.kt, Provider/src/test/java/com/spotify/confidence/ConfidenceIntegrationTests.kt
All file i/o should now be contained behind the DiskStorage interface which will improve testability.
=> fix: Move apply cache into disk storage

Provider/build.gradle.kts
As a part of publishing to Maven Central, this PR adds declaration of licensing, developers, project links and source control management (scm).
=> fix: add pom declaration to maven publication

Provider/src/test/java/com/spotify/confidence/ConfidenceFeatureProviderTests.kt, Provider/src/test/java/com/spotify/confidence/StorageFileCacheTests.kt
We had [this error](https://github.com/spotify/confidence-openfeature-provider-kotlin/actions/runs/6458441725/job/17532155543#step:9:657) in one of the latest builds and since we are not really in control when the apply events are sent and retried, I believe it makes sense to always mock the `apply(x,y)` function on the client.
=> test: add forgotten mocks for apply

.github/workflows/release-please.yaml
This step [failed](https://github.com/spotify/confidence-openfeature-provider-kotlin/actions/runs/6457650157/job/17529664108) during the last release. Either we remove it or fix it somehow but I'm not perfectly sure why we have it.
cc @vahidlazio do you know?
=> ci: remove release step to upload aar

Provider/build.gradle.kts, Provider/src/main/java/com/spotify/confidence/apply/FlagApplierWithRetries.kt, Provider/src/main/java/com/spotify/confidence/client/serializers/Serializers.kt
This bumps the kotlinx-serialization dependency and fixes some minSDK 21 failures.
Fixes #98
=> chore: bump kotlinx-serialization to 1.6.0

Provider/src/test/java/com/spotify/confidence/ConfidenceIntegrationTests.kt
As we are cleaning up older unused Confidence orgs and moving the testing setup to new ones
=> ci: Update IntegrationTest flag

Provider/src/main/java/com/spotify/confidence/client/ConfidenceRemoteClient.kt, Provider/src/test/java/com/spotify/confidence/ConfidenceRemoteClientTests.kt
We never handled the response coming back from the client when doing the apply request.
This is used to decide the state of the apply event and if we try to send it again.
=> fix: correctly handle apply response in event processor

Provider/src/main/java/com/spotify/confidence/ConfidenceFeatureProvider.kt, Provider/src/main/java/com/spotify/confidence/client/CommonTypes.kt, Provider/src/main/java/com/spotify/confidence/client/ConfidenceRemoteClient.kt
Previously, the region would default to Europe. This PR is changing this to GLOBAL and is specifying a URL for that.
=> chore: add a default endpoint to the provider

ConfidenceDemoApp/src/main/java/com/example/confidencedemoapp/MainVm.kt, Provider/build.gradle.kts, Provider/src/main/java/com/spotify/confidence/ConfidenceFeatureProvider.kt, Provider/src/test/java/com/spotify/confidence/StorageFileCacheTests.kt, README.md
The reasons behind this change:
- This is currently not working as expected, since in case of `activateAndFetchAsync` the STALE event is emitted even if it shouldn't
- According to [this WIP Proposal](https://github.com/open-feature/spec/pull/241/files), no event is expected prior to "initialize". 
- The STALE event is not meant to indicate a "not-ready cache" anyway: it's meant be used only if the system detects a change of flag evaluation data (for the same evaluation context). From the same PR mentioned above, a new events will be introduced for context reconciliation: `PROVIDER_CONTEXT_PENDING` and `PROVIDER_CONTEXT_CHANGED` 
Similar to the Swift Provider change: https://github.com/spotify/confidence-openfeature-provider-swift/pull/78
=> fix: Remove STALE event

Provider/src/main/java/com/spotify/confidence/ConfidenceValue.kt
The provider defines its own `DateSerializer` so this is what we should use.
=> fix: use the local DateSerializer

Provider/src/main/java/com/spotify/confidence/Confidence.kt, Provider/src/main/java/com/spotify/confidence/EventSender.kt, Provider/src/main/java/com/spotify/confidence/EventSenderEngine.kt, Provider/src/main/java/com/spotify/confidence/EventSenderUploader.kt, Provider/src/test/java/com/spotify/confidence/EventSenderIntegrationTest.kt
Also minor changes in the various interfaces and how events are stored on disk
=> refactor: Add `message` container to `payload`

Provider/src/main/java/com/spotify/confidence/Confidence.kt, Provider/src/main/java/com/spotify/confidence/VisitorUtil.kt, Provider/src/test/java/com/spotify/confidence/ConfidenceIntegrationTests.kt, Provider/src/test/java/com/spotify/confidence/EventSenderIntegrationTest.kt, Provider/src/test/java/com/spotify/confidence/InMemorySharedPreferences.kt
While doing this I met with the issue of a stale context in a test.
Me and @vahidlazio decided that it made most sense with regards to our discussions this week to send back the actual value but also to signal in the `errorCode` that the evaluation may be stale.
The Open feature provider however "swallows" that error code.
=> feat: include persistent visitor id in context

Provider/build.gradle.kts, README.md, catalog-info.yaml
This PR is renaming references to the old repository name, bar CHANGELOG.
=> refactor: rename repository

release-please-config.json
The error in CI shows up related to some query failing, and I believe the 500 limit a few lines up might be the problem (since we haven't released in a while, the depth of our queries might have increased)
=> fix: Release please increase depth

Provider/build.gradle.kts
[0.3.0](https://github.com/open-feature/kotlin-sdk/compare/v0.2.3...v0.3.0) (2024-04-08)
⚠ BREAKING CHANGES
remove kotlinx.serialization dependency
🔄 Refactoring
remove kotlinx.serialization dependency ([3145d6c](https://github.com/open-feature/kotlin-sdk/commit/3145d6c41359598e8565a19d576863df82de6f16))
=> chore: update openfeature sdk version to 0.3.0

Confidence/src/main/java/com/spotify/confidence/AndroidLifecycleEventProducer.kt, Confidence/src/main/java/com/spotify/confidence/Confidence.kt, Confidence/src/main/java/com/spotify/confidence/EventProducer.kt
`previous_version` and `previous_build` are not available in iOS: removing for consistency.
Also changing the context keys for version and build for consistency: https://github.com/spotify/confidence-sdk-swift/pull/127
=> fix: Add version/build to context

Provider/src/main/java/com/spotify/confidence/openfeature/ConfidenceFeatureProvider.kt, Provider/src/test/java/com/spotify/confidence/openfeature/ConfidenceIntegrationTests.kt
Replicating https://github.com/spotify/confidence-sdk-swift/pull/141
=> refactor: Add ConfidenceForOF proxy for safe init

Confidence/src/main/java/com/spotify/confidence/ConfidenceValue.kt
expose the json representation of a confidence struct.
useful for where it's needed like Flutter without having to depend on kotlinx serialization in the flutter sdk.
=> feat: expose convert value to json

CONTRIBUTING.md, Confidence/api/Confidence.api, Confidence/build.gradle.kts, Provider/api/Provider.api, Provider/build.gradle.kts, build.gradle.kts
This PR adds a validation step to ensure that we do not change the public API without noticing.
The gradle `check` step (runs on CI builds) will validate the current API of the classes in the gradle project against the checked in file (`confidence/api/confidence.api` or `Provider/api/Provider.api`). If it detects changes in the API, it will fail like this:
`I added a String parameter to the flush function`
```
> Task :Confidence:apiCheck FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':Confidence:apiCheck'.
> API check failed for project Confidence.
--- /Users/nicklasl/src/confidence/confidence-openfeature-provider-kotlin/Confidence/api/Confidence.api
+++ /Users/nicklasl/src/confidence/confidence-openfeature-provider-kotlin/Confidence/build/api …
```
=> ci: add binary-compatibility-validator plugin

Confidence/src/main/java/com/spotify/confidence/Confidence.kt, Confidence/src/main/java/com/spotify/confidence/ConfidenceContext.kt, Confidence/src/main/java/com/spotify/confidence/EventSender.kt
Adding documentation to the public APIs.
=> docs: Add docs to public APIs

Confidence/api/Confidence.api, Confidence/src/main/java/com/spotify/confidence/Confidence.kt
There was a case for race conditions that could occur when calling putContext() followed by a awaitReconciliation() where the contextChanges updates did not trigger a fetchAndActivate before awaitReconciliation had finished.
Replaces https://github.com/spotify/confidence-sdk-android/pull/185
=> fix: await reconciliation bug

Confidence/src/main/java/com/spotify/confidence/EventSenderEngine.kt, Provider/api/Provider.api, Provider/build.gradle.kts, Provider/src/main/java/com/spotify/confidence/openfeature/ConfidenceFeatureProvider.kt, Provider/src/test/java/com/spotify/confidence/openfeature/ProviderIntegrationTest.kt
Bumping the OF SDK allows OF users to emit events using the Confidence Provider via the OpenFeature API.
=> feat(Provider): Add support for Tracking from OpenFeature

Confidence/api/Confidence.api, Confidence/build.gradle.kts, Confidence/src/main/java/com/spotify/confidence/Confidence.kt, Confidence/src/main/java/com/spotify/confidence/ConfidenceDeviceInfoContextProducer.kt, Confidence/src/main/java/com/spotify/confidence/ConfidenceValue.kt, Confidence/src/main/java/com/spotify/confidence/DebugLogger.kt, Confidence/src/main/java/com/spotify/confidence/EventSender.kt, Confidence/src/main/java/com/spotify/confidence/Producer.kt, Confidence/src/test/java/com/spotify/confidence/ConfidenceEvaluationTest.kt, Confidence/src/test/java/com/spotify/confidence/ConfidenceProducerIntegrationTest.kt, Confidence/src/test/java/com/spotify/confidence/DebugLoggerImplTest.kt, Confidence/src/test/java/com/spotify/confidence/StorageFileCacheTests.kt, Confidence/src/test/java/com/spotify/confidence/fakes/FakeDiskStorage.kt, Confidence/src/test/java/com/spotify/confidence/fakes/FakeEventSenderEngine.kt, Confidence/src/test/java/com/spotify/confidence/fakes/FakeFlagApplierClient.kt, Confidence/src/test/java/com/spotify/confidence/fakes/FakeFlagResolver.kt, ConfidenceDemoApp/build.gradle.kts, ConfidenceDemoApp/src/main/java/com/example/confidencedemoapp/AndroidLifecycleEventProducer.kt, ConfidenceDemoApp/src/main/java/com/example/confidencedemoapp/MainVm.kt, README.md
The main work here is to stop exposing the `AndroidLifecycleEventProducer` and to restructure how we expose the ?`Producer` interface.
Keeping multiple breaking changes in one PR.
=> feat!: refactor context provider

Confidence/src/main/java/com/spotify/confidence/Confidence.kt, Confidence/src/main/java/com/spotify/confidence/DebugLogger.kt, Confidence/src/main/java/com/spotify/confidence/EventSenderEngine.kt, Confidence/src/main/java/com/spotify/confidence/EventSenderUploader.kt, Confidence/src/main/java/com/spotify/confidence/RemoteFlagResolver.kt, Confidence/src/test/java/com/spotify/confidence/DebugLoggerFake.kt, Confidence/src/test/java/com/spotify/confidence/DebugLoggerImplTest.kt
This makes it easier (or actually possible) to notice when a request does not succeed.
=> fix: add additional logging to detect network issues

Confidence/api/Confidence.api, Confidence/src/main/java/com/spotify/confidence/Confidence.kt, Provider/src/main/java/com/spotify/confidence/openfeature/ConfidenceFeatureProvider.kt
API change is only adding a param (and with a default value) so it shouldn't be breaking.
=> fix: skip extra resolve when initialising ConfidenceProvider

Confidence/build.gradle.kts, ConfidenceDemoApp/build.gradle.kts, Provider/build.gradle.kts, build.gradle.kts, gradle/libs.versions.toml
This PR migrates our monorepo to adopt the TOML Version Catalog approach for managing dependencies, plugins, and version numbers. By leveraging the Version Catalog feature we aim to improve dependency management, promote consistency across modules, and streamline dependency updates. ✨✨✨
=> chore: move to toml for version catalog

Confidence/src/main/java/com/spotify/confidence/Confidence.kt, Confidence/src/test/java/com/spotify/confidence/ConfidenceContextualTests.kt
With this change you can decide the visitor ID context key that the SDK will use.
The SDK will also respect if you pass an initial context that already has the (potentially custom) visitor id key and not overwrite it.
=> feat: configurable visitor id key

Confidence/src/main/java/com/spotify/confidence/Confidence.kt, Confidence/src/test/java/com/spotify/confidence/DebugLoggerIntegrationTest.kt, Provider/src/test/java/com/spotify/confidence/openfeature/DebugLoggerOpenFeatureIntegrationTest.kt
Previously the resulting json contained the context value type which meant that while the base64 decoding worked in the Confidence app the resolve was not working properly.
The Confidence SDK was incorrectly serializing context with type wrapper objects:
```json
{
"flag": "flags/test-flag",
"context": {
"visitor_id": {"string": "bcd97b13-ddad-4ee8-9331-aeac06370bd9"},
"targeting_key": {"string": "test-user-123"},
"user": {
"map": {
"country": {"string": "SE"},
"age": {"integer": 25},
"product": {"string": "premium"},
"fraud-score": {"double": 0.7}
}
}
},
"clientKey": "test-client-secret"
}
```
Issues:
- Values wrapped in type objects like `{"string": "value"}, {"integer": 25}, {"double": 0.7}`
- Nested structures wrapped in `{"map": {...}}`
- Not usable with the Resolve tester tool
The …
=> fix: correct format on resolve tester base64 encoded json
